language: node_js
node_js:
  - 12
  - 14

install:
  - npm install

script:
  - npm test

deploy:
  - provider: npm
    skip_cleanup: true
    email: $npm_mail
    api_key: $npm_key
    on:
      tags: true
